export default ScreenNames = {
  Onboading: 'OnBoarding',
  LoginScreen: 'LoginScreen',
  SignupScreen: 'SignupScreen',
  ForgotPasswordScreen: 'ForgotPasswordScreen',
  VerificationScreen: 'VerificationScreen',
  EnterDetails: 'EnterDetails',
  TopTabNavigator: 'TopTabNavigator',
  TopTabScreens: {
    HomeScreen: 'Home',
    StatusScreen: 'Status',
    ProfileScreen: 'Profile',
  },
  TopTabInnerScreens: {
    Appearence: 'Appearence',
    PrivacyNSecurity: 'PrivacyAndSecurity',
    BackupNRestore: 'BackupAndRestore',
    ProfileSettings: 'ProfileSettings',
  },
  NewChatPage: 'NewChatPage',
  ChatPage: 'ChatPage',
  GroupChatPage: 'GroupChatPage',
  ChatInfoScreen: 'ChatInfoScreen',
  GroupChatInfoScreen: 'GroupChatInfoScreen',
  EditGroupScreen: 'EditGroupScreen',
};
